### ISSUE TITLE
Interface seems frozen

### ISSUE THREAD

**Issue by Vectornaut** [KartoffelChipss/HexPick#1]
I can launch HexPick and enter text into the text boxes, but nothing affects the color swatches shown next to the text boxes. Clicking the eyedropper button does nothing. (Is it supposed to do anything? Do I just not understand the interface?)

OS: Ubuntu 22.04.4
Desktop: Gnome 42.9
Window manager: Wayland

**Comment by KartoffelChipss** [comment]
It seems to be a problem with the snap that you download from the store. If you use one of the releases from GitHub it should work fine

**Comment by Vectornaut** [comment]
I just tried cloning the repo, running `npm install`, and then launching with `npm run start`, but the interface is frozen in the same way.

**Comment by Vectornaut** [comment]
I've now also tried installing the .deb from the release page. The interface is frozen in the same way.

The next natural thing to try would be building the installer from source, but I seem to be missing a dependency, and I don't have the energy to hunt it down.

**Comment by KartoffelChipss** [comment]
It seems to be a problem with Wayland. Try "npm install electron@latest" and then run the app with "npm run start"

**Comment by Vectornaut** [comment]
When I installed `electron@latest`, I got a runtime error during installation (shown at the end). Launching the app with `npm run start` then immediately generated these error messages:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[94131:0308/021433.245949:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```
Clicking the picker button generated an additional error message:
```
[ERROR] getColor Error: Command failed: /home/vectornaut/Applications/HexPick/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /tmp/temp-screenshot.png
/home/vectornaut/Applications/HexPick/node_modules/electron-color-picker/library/linux/linux-scrot/scrot: error while loading shared libraries: libgiblib.so.1: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (node:child_process:409:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/home/vectornaut/Applications/HexPick/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /tmp/temp-screenshot.png'
}
```
#### NPM build error
```
npm ERR! code 1
npm ERR! path /home/vectornaut/Applications/HexPick/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /home/vectornaut/Applications/HexPick/node_modules/electron/install.js:45
npm ERR!   checksums: process.env.electron_use_remote_checksums ?? process.env.npm_config_electron_use_remote_checksums ? undefined : require('./checksums.json'),
npm ERR!                                                         ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '?'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
npm ERR!     at internal/main/run_main_module.js:17:47
```

**Comment by KartoffelChipss** [comment]
There is a new release on GitHub, that should fix your problem:
https://github.com/KartoffelChipss/HexPick/releases/tag/v1.0.1

**Comment by Vectornaut** [comment]
I installed v1.0.1 from the .deb. Mousing over the app window generates errors like this:
```
[98597:0308/025911.171334:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```
Clicking the picker button generates this error:
```
[ERROR] getColor Error: Command failed: /opt/HexPick/resources/app.asar.unpacked/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /tmp/temp-screenshot.png
/opt/HexPick/resources/app.asar.unpacked/node_modules/electron-color-picker/library/linux/linux-scrot/scrot: error while loading shared libraries: libgiblib.so.1: cannot open shared object file: No such file or directory

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/opt/HexPick/resources/app.asar.unpacked/node_modules/electron-color-picker/library/linux/linux-scrot/scrot /tmp/temp-screenshot.png'
}
```
